# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
        environment:
        required: true
        default: "Stop"
        description: Choose browser
        type: choice
        options: 
        - Stop
        - Start
    
